#!/bin/bash
# Run createTest.php on an EMPTY Zoph database to fill the database with the same
# data as the data in the provided db.xml. You should normally not need to run 
# this, unless you make changes to the testdata and need to create a new db.xml
#
# You will need to adopt the below to your local situation

echo -n "Password: "
read -s PASSWORD

echo "Drop Database zophtest:"
mysqladmin -u root -p"$PASSWORD" drop zophtest
echo "Create database zophtest:"
mysql -u root -p"$PASSWORD" -e "CREATE DATABASE zophtest CHARACTER SET utf8 COLLATE utf8_general_ci"
echo "Grant permissions:"
mysql -u root -p"$PASSWORD" -e "grant all on zophtest.* to zoph@'%' identified by \"$PASSWORD\""
echo "Import default SQL data:"
mysql -u root -p"$PASSWORD" zophtest < ../sql/zoph.sql
echo "Create test database:"
./createTestData/createTest.php
echo "Dump data to XML file:"
mysqldump -t -u root -p"$PASSWORD" --xml zophtest > db.xml
