<?php
/*
 * This file is part of Zoph.
 *
 * Zoph is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * Zoph is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with Zoph; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */

    require_once("include.inc.php");

    $_off = getvar("_off");
    $_pause = getvar("_pause");
    $_random = getvar("_random");

    if (!$_off)  { $_off = 0; }
    $offset = $_off;

    $thumbnails;
    $num_photos = get_photos($request_vars, $offset, 1, $thumbnails, $user);

/* I am not sure if this is always correct; for all the other files the charset is generated by rtplang.class.php, but this file doesn't call that class... have to investigate */

    $charset = "iso-8859-1";
    $num_thumbnails = sizeof($thumbnails);

    if  ($num_thumbnails) {
        if ($_random) {
            $title = translate("random photo ") . ($offset + 1);
        }
        else {
            $title = sprintf(translate("photo %s of %s"),  ($offset + 1) , $num_photos);
        }
    }
    else {
        header("Location: " . add_sid("photos.php?" . update_query_string($request_vars, "_off", 0)));
    }

    $newoffset = $offset + 1;

    $new_qs = $QUERY_STRING;
    if (strpos($QUERY_STRING, "_off=") > 0) {
        $new_qs = str_replace("_off=$offset", "_off=$newoffset", $new_qs);
    }
    else {
        if ($new_qs) {
            $new_qs .= "&";
        }
        $new_qs .= "_off=$newoffset";
    }

    $header = "";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=<?php echo $charset;?>">
<link TYPE="text/css" REL="stylesheet" HREF="<?php echo CSS_SHEET ?>">
<?php
if (!$_pause) {
        // bug#667480: header() didn't work with IE on Mac
        // manually set http-equiv instead
        //header("Refresh: $SLIDESHOW_TIME;URL=$PHP_SELF?$new_qs");
        $header = "<meta http-equiv=\"refresh\" content=\"$SLIDESHOW_TIME;URL=$PHP_SELF?$new_qs\">\n";
    }
    else {
        $new_qs = str_replace("_pause=1", "", $new_qs);
    }

    $table_width = " width=\"" . DEFAULT_TABLE_WIDTH . "\"";
?>
<?php echo $header ?>
<title>Zoph - Slideshow</title>
</head>
<body>

<table class="page">
  <tr>
    <td>
      <table class="titlebar">
        <tr>
          <th><h1><?php echo $title ?></h1></th>
          <td class="actionlink">
          [
<?php
    if ($_pause) {
?>
            <a href="<?php echo $PHP_SELF . '?' . $new_qs ?>"><?php echo translate("continue") ?></a> |
<?php
    }
    else {
?>
            <a href="<?php echo $PHP_SELF . '?' . $QUERY_STRING . '&' . "_pause=1" ?>"><?php echo translate("pause") ?></a> |
<?php
    }
?>
            <a href="photos.php?<?php echo str_replace("_off=$offset", "_off=0", $QUERY_STRING) ?>"><?php echo translate("stop") ?></a> |
            <a href="photo.php?<?php echo $QUERY_STRING ?>"><?php echo translate("open") ?></a>
          ]
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td>
      <table class="main">
<?php
    if ($num_thumbnails <= 0) {
?>
        <tr>
          <td>
       <?php echo translate("No photos were found for this slideshow.") ?>
          </td>
        </tr>
<?php
    }
    else {
        $photo = $thumbnails[0];
        $photo->lookup();
?>
        <tr>
          <td colspan="2" class="photohdr">
            <?php echo $photo->get_fullsize_link($photo->get("name")) ?> :
            <?php echo $photo->get("width") ?> x <?php echo $photo->get("height") ?>,
         <?php echo $photo->get("size") ?> <?php echo translate("bytes") ?>
          </td>
        </tr>
        <tr>
          <td colspan="2" class="photo">
            <?php echo $photo->get_fullsize_link($photo->get_midsize_img()) ?>
          </td>
        </tr>
<?php
        if ($people_links = get_photo_person_links($photo)) {
?>
        <tr>
          <td colspan="2" class="personlink">
            <?php echo $people_links ?>
          </td>
        </tr>
<?php
        }
?>
<?php echo create_field_html($photo->get_display_array(), 2) ?>
<?php
        if ($photo->get("description")) {
?>
        <tr>
          <td colspan="2" class="description">
            <hr class="wide">
            <?php echo $photo->get("description") ?>
          </td>
        </tr>
<?php
        }
    } // if photos
?>
      </table>
    </td>
  </tr>
</table>

<?php require_once("footer.inc.php"); ?>
